set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

find_program(_clang_c NAMES clang-17)
find_program(_clang_cxx NAMES clang++-17)
if(_clang_c AND _clang_cxx)
    set(triple aarch64-linux-gnu)
    set(CMAKE_C_COMPILER "${_clang_c}")
    set(CMAKE_CXX_COMPILER "${_clang_cxx}")
    set(CMAKE_C_COMPILER_TARGET ${triple})
    set(CMAKE_CXX_COMPILER_TARGET ${triple})
else()
    find_program(_gcc_c NAMES aarch64-linux-gnu-gcc aarch64-redhat-linux-gcc)
    if(NOT _gcc_c)
        message(FATAL_ERROR "No aarch64 cross-compiler found (tried clang-17, aarch64-linux-gnu-gcc, aarch64-redhat-linux-gcc)")
    endif()
    get_filename_component(_gcc_name "${_gcc_c}" NAME)
    string(REGEX REPLACE "-gcc$" "" triple "${_gcc_name}")
    set(CMAKE_C_COMPILER "${_gcc_c}")
    set(CMAKE_CXX_COMPILER "${triple}-g++")
endif()

if(EXISTS /usr/${triple})
    set(CMAKE_SYSROOT /usr/${triple})
endif()

set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE arm64)
set(CPACK_RPM_PACKAGE_ARCHITECTURE aarch64)

set(ENV{PKG_CONFIG_PATH} /usr/lib/${triple}/pkgconfig)
