set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

find_program(_clang_c NAMES clang-17)
find_program(_clang_cxx NAMES clang++-17)
if(_clang_c AND _clang_cxx)
    set(triple arm-linux-gnueabihf)
    set(CMAKE_C_COMPILER "${_clang_c}")
    set(CMAKE_CXX_COMPILER "${_clang_cxx}")
    set(CMAKE_C_COMPILER_TARGET ${triple})
    set(CMAKE_CXX_COMPILER_TARGET ${triple})
else()
    find_program(_gcc_c NAMES arm-linux-gnueabihf-gcc arm-redhat-linux-gnueabihf-gcc)
    if(NOT _gcc_c)
        message(FATAL_ERROR "No arm cross-compiler found (tried clang-17, arm-linux-gnueabihf-gcc, arm-redhat-linux-gnueabihf-gcc)")
    endif()
    get_filename_component(_gcc_name "${_gcc_c}" NAME)
    string(REGEX REPLACE "-gcc$" "" triple "${_gcc_name}")
    set(CMAKE_C_COMPILER "${_gcc_c}")
    set(CMAKE_CXX_COMPILER "${triple}-g++")
endif()


set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE armhf)
set(CPACK_RPM_PACKAGE_ARCHITECTURE armv7hl)

set(ENV{PKG_CONFIG_PATH} /usr/lib/${triple}/pkgconfig)
