name: OpenZiti Tunneler Build Action
description: Builds ziti-edge-tunnel binary and Linux package
author: NetFoundry
inputs:
  arch:
    description: The cmake preset used by entrypoint.sh when running cmake
    required: false
  config:
    description: The cmake build configuration used by entrypoint.sh when running cmake
    required: false
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.arch }}
    - ${{ inputs.config }}
