name: Nix Build Test Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-v*
  pull_request:
    branches:
      - main
      - release-v*

# cancel older, redundant runs of same workflow on same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  nix-build:
    name: Build Nix Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build Ziti Edge Tunnel
        run: |
          nix build
          ./result/bin/ziti-edge-tunnel version
